version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taritme-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
