version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taritme-backend
    restart: always # always start docker after reboot or fresh start VPS
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - path: .env
        required: true
